### ISSUE TITLE
feat: initializing dropdown bars to have text

### ISSUE THREAD

**Issue by AyshaAraien** [AspireUni/Aspire#43]
This task is to initialize the two dropdown bars to have placeholder text prompting the user to select their options. See the picture below for an example.

![Screen Shot 2020-05-14 at 7.23.03 PM.png](https://images.zenhubusercontent.com/5ebdcfeb2546988ef1dc95fa/954cae5e-5376-4b51-a6cc-18153b3217ab)

**Comment by HelenGezahegn** [comment]
@AyshaAraien Is this task still relevant or can it be closed given your current PR?
